HasPokemonMsg:
    .string "Thanks for showing your Pokémon! You may pass.$"
NoPokemonMsg:
    .string "Sorry, you need a Pokémon to pass.$"

DreamMap_Text_HelloWorld:
    .string "Hello, World!$"

DreamMap_Text_GoodYouCanPass:
    .string "good job you can now strengthen your\n"
    .string "team by challenging rare pokemons at\l"
    .string "the rooftop$"

DreamMap_Text_NoPokemon:
    .string "Why are geh, you don't have any Pokémon?$"

DreamMap_Text_MoveAside:
    .string "move aside please this is for people\n"
    .string "who actually have Pokémon.$"

