HasPokemonMsg:
    .string "Thanks for showing your Pokémon! You may pass.$"
NoPokemonMsg:
    .string "Sorry, you need a Pokémon to pass.$"

DreamMap_Text_HelloWorld:
    .string "Hello, World!$"

DreamMap_Text_GoodYouCanPass:
    .string "good job you can now strengthen your\n"
    .string "team by challenging rare pokemons at\l"
    .string "the rooftop$"

DreamMap_Text_NoPokemon:
    .string "Why are geh, you don't have any Pokémon?$"

DreamMap_Text_MoveAside:
    .string "move aside please this is for people\n"
    .string "who actually have Pokémon.$"

DreamMap_Text_HereSomePrizeItems:
	.string "Here are some prize items for reaching\n"
	.string "this stage of the game.$"

DreamMap_Text_OhGodForgotHMs:
	.string "Oh god! I almost forgot!\n"
	.string "You do not have HMs!\p"
	.string "You need these to help you…$"

DreamMap_Text_PartyFullWillSendToPC:
	.string "Your party is full!\n"
	.string "The POKéMONs will be sent to your PC.$"

DreamMap_Text_MarillSentToPC:
	.string "MARILL was sent to your PC.$"

DreamMap_Text_GeodudeSentToPC:
	.string "GEODUDE was sent to your PC.$"

DreamMap_Text_ReceivedHMPokemon:
	.string "Use MARILL to SURF on water and\n"
	.string "GEODUDE to ROCK SMASH the rocks!$"

