RooftopField_Text_GrassSign:
	.string "Grass Field Area\n"
	.string "Home to grass-type starters from\p"
	.string "different generations.$"

RooftopField_Text_WaterSign:
	.string "Water Field Area\n"
	.string "Home to water-type starters from\p"
	.string "different generations.$"

RooftopField_Text_RockSign:
	.string "Navel Rock Area\n"
	.string "Home to fire-type starters from\p"
	.string "different generations.$"
