@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
.text
	.align	2, 0
	.globl	GetPokedexCategoryName
	.type	 GetPokedexCategoryName,function
	.thumb_func
GetPokedexCategoryName:
	add	r1, r0, #0
	lsl	r1, r1, #0x10
	lsr	r1, r1, #0x10
	lsl	r0, r1, #0x3
	add	r0, r0, r1
	lsl	r0, r0, #0x2
	ldr	r1, .L3
	add	r0, r0, r1
	bx	lr
.L4:
	.align	2, 0
.L3:
	.word	gPokedexEntries
.Lfe1:
	.size	 GetPokedexCategoryName,.Lfe1-GetPokedexCategoryName
	.align	2, 0
	.globl	GetPokedexHeightWeight
	.type	 GetPokedexHeightWeight,function
	.thumb_func
GetPokedexHeightWeight:
	push	{lr}
	lsl	r0, r0, #0x10
	lsr	r2, r0, #0x10
	lsl	r1, r1, #0x18
	lsr	r1, r1, #0x18
	cmp	r1, #0
	beq	.L7	@cond_branch
	cmp	r1, #0x1
	beq	.L8	@cond_branch
	mov	r0, #0x1
	b	.L11
.L7:
	ldr	r0, .L13
	lsl	r1, r2, #0x3
	add	r1, r1, r2
	lsl	r1, r1, #0x2
	add	r1, r1, r0
	ldrh	r0, [r1, #0xc]
	b	.L12
.L14:
	.align	2, 0
.L13:
	.word	gPokedexEntries
.L8:
	ldr	r0, .L15
	lsl	r1, r2, #0x3
	add	r1, r1, r2
	lsl	r1, r1, #0x2
	add	r1, r1, r0
	ldrh	r0, [r1, #0xe]
.L12:
.L11:
	pop	{r1}
	bx	r1
.L16:
	.align	2, 0
.L15:
	.word	gPokedexEntries
.Lfe2:
	.size	 GetPokedexHeightWeight,.Lfe2-GetPokedexHeightWeight
	.align	2, 0
	.globl	GetSetPokedexFlag
	.type	 GetSetPokedexFlag,function
	.thumb_func
GetSetPokedexFlag:
	push	{lr}
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	lsl	r1, r1, #0x18
	lsr	r1, r1, #0x18
	mov	r2, #0x0
	bl	DexScreen_GetSetPokedexFlag
	lsl	r0, r0, #0x18
	asr	r0, r0, #0x18
	pop	{r1}
	bx	r1
.Lfe3:
	.size	 GetSetPokedexFlag,.Lfe3-GetSetPokedexFlag
	.align	2, 0
	.globl	GetNationalPokedexCount
	.type	 GetNationalPokedexCount,function
	.thumb_func
GetNationalPokedexCount:
	push	{r4, r5, r6, r7, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	mov	r5, #0x0
	mov	r0, #0x0
	ldr	r7, .L32
.L22:
	cmp	r6, #0
	beq	.L24	@cond_branch
	cmp	r6, #0x1
	beq	.L26	@cond_branch
	add	r4, r0, #0x1
	b	.L21
.L33:
	.align	2, 0
.L32:
	.word	0x181
.L24:
	add	r4, r0, #0x1
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	mov	r1, #0x0
	b	.L31
.L26:
	add	r4, r0, #0x1
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	mov	r1, #0x1
.L31:
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L21	@cond_branch
	add	r0, r5, #0x1
	lsl	r0, r0, #0x10
	lsr	r5, r0, #0x10
.L21:
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, r7
	bls	.L22	@cond_branch
	add	r0, r5, #0
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
.Lfe4:
	.size	 GetNationalPokedexCount,.Lfe4-GetNationalPokedexCount
	.align	2, 0
	.globl	GetKantoPokedexCount
	.type	 GetKantoPokedexCount,function
	.thumb_func
GetKantoPokedexCount:
	push	{r4, r5, r6, lr}
	lsl	r0, r0, #0x18
	lsr	r6, r0, #0x18
	mov	r5, #0x0
	mov	r0, #0x0
.L38:
	cmp	r6, #0
	beq	.L40	@cond_branch
	cmp	r6, #0x1
	beq	.L42	@cond_branch
	add	r4, r0, #0x1
	b	.L37
.L40:
	add	r4, r0, #0x1
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	mov	r1, #0x0
	b	.L47
.L42:
	add	r4, r0, #0x1
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	mov	r1, #0x1
.L47:
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L37	@cond_branch
	add	r0, r5, #0x1
	lsl	r0, r0, #0x10
	lsr	r5, r0, #0x10
.L37:
	lsl	r0, r4, #0x10
	lsr	r0, r0, #0x10
	cmp	r0, #0x96
	bls	.L38	@cond_branch
	add	r0, r5, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
.Lfe5:
	.size	 GetKantoPokedexCount,.Lfe5-GetKantoPokedexCount
	.align	2, 0
	.globl	HasAllHoennMons
	.type	 HasAllHoennMons,function
	.thumb_func
HasAllHoennMons:
	push	{r4, lr}
	mov	r0, #0x0
.L52:
	add	r0, r0, #0x1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	add	r0, r4, #0
	bl	HoennToNationalOrder
	lsl	r0, r0, #0x10
	lsr	r0, r0, #0x10
	mov	r1, #0x1
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	bne	.L51	@cond_branch
	mov	r0, #0x0
	b	.L55
.L51:
	add	r0, r4, #0
	cmp	r0, #0xc7
	bls	.L52	@cond_branch
	mov	r0, #0x1
.L55:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe6:
	.size	 HasAllHoennMons,.Lfe6-HasAllHoennMons
	.align	2, 0
	.globl	HasAllKantoMons
	.type	 HasAllKantoMons,function
	.thumb_func
HasAllKantoMons:
	push	{r4, lr}
	mov	r0, #0x0
.L60:
	add	r0, r0, #0x1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	add	r0, r4, #0
	mov	r1, #0x1
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	bne	.L59	@cond_branch
	mov	r0, #0x0
	b	.L63
.L59:
	add	r0, r4, #0
	cmp	r0, #0x95
	bls	.L60	@cond_branch
	mov	r0, #0x1
.L63:
	pop	{r4}
	pop	{r1}
	bx	r1
.Lfe7:
	.size	 HasAllKantoMons,.Lfe7-HasAllKantoMons
	.align	2, 0
	.globl	HasAllMons
	.type	 HasAllMons,function
	.thumb_func
HasAllMons:
	push	{r4, r5, lr}
	mov	r0, #0x0
.L68:
	add	r0, r0, #0x1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	add	r0, r4, #0
	mov	r1, #0x1
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L84	@cond_branch
	add	r0, r4, #0
	cmp	r0, #0x95
	bls	.L68	@cond_branch
	mov	r0, #0x97
.L74:
	add	r0, r0, #0x1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	add	r0, r4, #0
	mov	r1, #0x1
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	beq	.L84	@cond_branch
	add	r0, r4, #0
	cmp	r0, #0xf7
	bls	.L74	@cond_branch
	mov	r0, #0xfb
	ldr	r5, .L85
.L80:
	add	r0, r0, #0x1
	lsl	r0, r0, #0x10
	lsr	r4, r0, #0x10
	add	r0, r4, #0
	mov	r1, #0x1
	bl	GetSetPokedexFlag
	lsl	r0, r0, #0x18
	cmp	r0, #0
	bne	.L79	@cond_branch
.L84:
	mov	r0, #0x0
	b	.L83
.L86:
	.align	2, 0
.L85:
	.word	0x17f
.L79:
	add	r0, r4, #0
	cmp	r0, r5
	bls	.L80	@cond_branch
	mov	r0, #0x1
.L83:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
.Lfe8:
	.size	 HasAllMons,.Lfe8-HasAllMons
.text
	.align	2, 0 @ Don't pad with nop

