MyText::
	.string "Hello, there.\p"
	.string "You can refer to me in scripts\n or C code.$"
 
PreMoveText::
	.string "Hello, lets check if you have a pokemon,\n" 
	.string "and if you do I'll let you pass.$"

MoveText::
	.string "I see you do have a pokemon in your party.\n ok I'll let you go.\p"
	.string "Be careful in the tall grass!$"

HelloWorld_TXT::
# 5 "../../data/maps/DreamMap/custom_test.pory"
	.string "Hello World$"

